In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('zillow_data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14723 entries, 0 to 14722
Columns: 272 entries, RegionID to 2018-04
dtypes: float64(219), int64(49), object(4)
memory usage: 30.6+ MB

In [4]:
df.columns

Index(['RegionID', 'RegionName', 'City', 'State', 'Metro', 'CountyName',
       'SizeRank', '1996-04', '1996-05', '1996-06',
       ...
       '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12',
       '2018-01', '2018-02', '2018-03', '2018-04'],
      dtype='object', length=272)

In [5]:
df.City

0                    Chicago
1                   McKinney
2                       Katy
3                    Chicago
4                    El Paso
                ...
14718               Ashfield
14719              Woodstock
14720                  Berea
14721    Mount Crested Butte
14722               Mesquite
Name: City, Length: 14723, dtype: object

In [6]:
df

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
0,84654,60657,Chicago,IL,Chicago,Cook,1,334200.0,335400.0,336500.0,...,1005500,1007500,1007800,1009600,1013300,1018700,1024400,1030700,1033800,1030600
1,90668,75070,McKinney,TX,Dallas-Fort Worth,Collin,2,235700.0,236900.0,236700.0,...,308000,310000,312500,314100,315000,316600,318100,319600,321100,321800
2,91982,77494,Katy,TX,Houston,Harris,3,210400.0,212200.0,212200.0,...,321000,320600,320200,320400,320800,321200,321200,323000,326900,329900
3,84616,60614,Chicago,IL,Chicago,Cook,4,498100.0,500900.0,503100.0,...,1289800,1287700,1287400,1291500,1296600,1299000,1302700,1306400,1308500,1307000
4,93144,79936,El Paso,TX,El Paso,El Paso,5,77300.0,77300.0,77300.0,...,119100,119400,120000,120300,120300,120300,120300,120500,121000,121500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14718,58333,1338,Ashfield,MA,Greenfield Town,Franklin,14719,94600.0,94300.0,94000.0,...,216800,217700,218600,218500,218100,216400,213100,209800,209200,209300
14719,59107,3293,Woodstock,NH,Claremont,Grafton,14720,92700.0,92500.0,92400.0,...,202100,208400,212200,215200,214300,213100,213700,218300,222700,225800
14720,75672,40404,Berea,KY,Richmond,Madison,14721,57100.0,57300.0,57500.0,...,121800,122800,124600,126700,128800,130600,131700,132500,133000,133400
14721,93733,81225,Mount Crested Butte,CO,NaN,Gunnison,14722,191100.0,192400.0,193700.0,...,662800,671200,682400,695600,695500,694700,706400,705300,681500,664400
14722,95851,89155,Mesquite,NV,Las Vegas,Clark,14723,176400.0,176300.0,176100.0,...,333800,336400,339700,343800,346800,348900,350400,353000,356000,357200

In [7]:
list(df.Metro)

['Chicago',
 'Dallas-Fort Worth',
 'Houston',
 'Chicago',
 'El Paso',
 'Houston',
 'New York',
 'Chicago',
 'Houston',
 'San Francisco',
 'New York',
 'The Villages',
 'New York',
 'New York',
 'Nashville',
 'Los Angeles-Long Beach-Anaheim',
 'Chicago',
 'Nashville',
 'Austin',
 'Chicago',
 'New York',
 'New York',
 'Houston',
 'Houston',
 'Charlotte',
 'El Paso',
 'McAllen',
 'San Francisco',
 'Atlanta',
 'Washington',
 'Los Angeles-Long Beach-Anaheim',
 'San Antonio',
 'Austin',
 'Washington',
 'Dallas-Fort Worth',
 'New York',
 'New York',
 'Clarksville',
 'Houston',
 'St. Louis',
 'Chicago',
 'Houston',
 'Atlanta',
 'Oklahoma City',
 'Houston',
 'Houston',
 'New York',
 'New York',
 'Chicago',
 'New York',
 'Chicago',
 'Atlanta',
 'Dallas-Fort Worth',
 'New York',
 'Dallas-Fort Worth',
 'Charlotte',
 'Phoenix',
 'New York',
 'New York',
 'Baltimore',
 'Miami-Fort Lauderdale',
 'Brownsville',
 'Virginia Beach',
 'Houston',
 'San Francisco',
 'Atlanta',
 'Austin',
 'Seattle',
 'Houston',
 'Dallas-Fort Worth',
 'New York',
 'San Antonio',
 'New York',
 'New York',
 'Chicago',
 'Los Angeles-Long Beach-Anaheim',
 'San Francisco',
 'Austin',
 'Atlanta',
 'Chicago',
 'Cleveland',
 'Dallas-Fort Worth',
 'Miami-Fort Lauderdale',
 'Miami-Fort Lauderdale',
 'Miami-Fort Lauderdale',
 'New York',
 'Los Angeles-Long Beach-Anaheim',
 'Ann Arbor',
 'Boston',
 'Virginia Beach',
 'Los Angeles-Long Beach-Anaheim',
 'Kansas City',
 'Cleveland',
 'Sacramento',
 'Los Angeles-Long Beach-Anaheim',
 'New York',
 'Los Angeles-Long Beach-Anaheim',
 'Tucson',
 'Austin',
 'New York',
 'New York',
 'Atlanta',
 'Jacksonville',
 'Nashville',
 'Napa',
 'Chicago',
 'New York',
 'Los Angeles-Long Beach-Anaheim',
 'Phoenix',
 'San Diego',
 'Albuquerque',
 'Charlotte',
 'Hartford',
 'San Antonio',
 'Albuquerque',
 'Las Vegas',
 'Phoenix',
 'New York',
 'Lancaster',
 'Fresno',
 'Denver',
 'Detroit',
 'Phoenix',
 'McAllen',
 'Vallejo',
 'Pittsburgh',
 'Sacramento',
 'Columbus',
 'Cleveland',
 'Denver',
 'Miami-Fort Lauderdale',
 'Washington',
 'Miami-Fort Lauderdale',
 'Los Angeles-Long Beach-Anaheim',
 'Columbus',
 'Portland',
 'Dallas-Fort Worth',
 'Riverside',
 'New York',
 'Yuma',
 'New York',
 'Ithaca',
 'Springfield',
 'Seattle',
 'Houston',
 'Los Angeles-Long Beach-Anaheim',
 'Sacramento',
 'Fort Myers',
 'Cleveland',
 'Boston',
 'Chicago',
 nan,
 'Cincinnati',
 'Dallas-Fort Worth',
 'Tampa',
 'Los Angeles-Long Beach-Anaheim',
 'New York',
 'Chicago',
 'New York',
 'Columbia',
 'Lafayette-West Lafayette',
 'Seattle',
 'Riverside',
 'Dallas-Fort Worth',
 'San Diego',
 'Los Angeles-Long Beach-Anaheim',
 'Columbus',
 nan,
 'Chicago',
 'Chicago',
 'Dallas-Fort Worth',
 'Fayetteville',
 'Raleigh',
 'Las Vegas',
 'Charlotte',
 'Dallas-Fort Worth',
 'Atlanta',
 'Atlanta',
 'El Paso',
 'Riverside',
 'Kennewick',
 'Washington',
 'Houston',
 'San Diego',
 'College Station',
 'Riverside',
 'San Francisco',
 'New York',
 'Raleigh',
 'Hagerstown',
 'New York',
 'New York',
 'Los Angeles-Long Beach-Anaheim',
 'Washington',
 'Philadelphia',
 'Las Vegas',
 'Albuquerque',
 'Columbus',
 'Richmond',
 'Indianapolis',
 'New York',
 'Riverside',
 'Virginia Beach',
 'Tulsa',
 'Los Angeles-Long Beach-Anaheim',
 'Riverside',
 'Jacksonville',
 'Baltimore',
 'San Diego',
 'Orlando',
 'Houston',
 'San Diego',
 'Orlando',
 'Atlanta',
 'New York',
 'Chicago',
 'Los Angeles-Long Beach-Anaheim',
 'Charlotte',
 'Fort Myers',
 'Los Angeles-Long Beach-Anaheim',
 'Ann Arbor',
 'Atlanta',
 'Miami-Fort Lauderdale',
 'Atlanta',
 'Atlanta',
 'Dallas-Fort Worth',
 'Miami-Fort Lauderdale',
 'Atlanta',
 'New York',
 'Jacksonville',
 'Orlando',
 'Chicago',
 'Greenville',
 'Riverside',
 'Nashville',
 'Virginia Beach',
 'Nashville',
 'San Diego',
 'Detroit',
 'Ventura',
 'Los Angeles-Long Beach-Anaheim',
 'Cleveland',
 'Sacramento',
 'Jacksonville',
 'San Jose',
 'Columbus',
 'Washington',
 'Washington',
 'Findlay',
 'Greeley',
 'Boston',
 'Los Angeles-Long Beach-Anaheim',
 'Tucson',
 'Washington',
 'Atlanta',
 'Virginia Beach',
 'Boston',
 'Miami-Fort Lauderdale',
 'Washington',
 'Columbia',
 'New York',
 'Miami-Fort Lauderdale',
 'Las Vegas',
 'Los Angeles-Long Beach-Anaheim',
 'Dallas-Fort Worth',
 'New York',
 'Daytona Beach',
 'Miami-Fort Lauderdale',
 'Albuquerque',
 'Zanesville',
 'Los Angeles-Long Beach-Anaheim',
 'Jonesboro',
 'New York',
 'Los Angeles-Long Beach-Anaheim',
 'New York',
 'Fargo',
 'Cleveland',
 'Dallas-Fort Worth',
 'New York',
 'Houston',
 'Port St. Lucie',
 'San Francisco',
 'Philadelphia',
 'Austin',
 'Chicago',
 'Eugene',
 'Columbus',
 'Miami-Fort Lauderdale',
 'Dallas-Fort Worth',
 'San Jose',
 'Washington',
 'Rochester',
 'Virginia Beach',
 'Riverside',
 'Los Angeles-Long Beach-Anaheim',
 'Birmingham',
 'Atlanta',
 'Hot Springs',
 'Los Angeles-Long Beach-Anaheim',
 'Charlotte',
 'Denver',
 'Jacksonville',
 'Vallejo',
 'Durham',
 'College Station',
 'Atlanta',
 'Columbus',
 'Los Angeles-Long Beach-Anaheim',
 'New York',
 'Las Vegas',
 'San Francisco',
 'Fort Collins',
 'McAllen',
 'Lansing',
 'St. Louis',
 'Frankfort',
 'Baltimore',
 'Charleston',
 'Chicago',
 'New York',
 'Orlando',
 'Houston',
 'Virginia Beach',
 'Richmond',
 'Chicago',
 'Bowling Green',
 'Chillicothe',
 'Atlanta',
 'Winston-Salem',
 'Philadelphia',
 'Buffalo',
 'Seattle',
 'Chicago',
 'San Francisco',
 'Fresno',
 'Dallas-Fort Worth',
 'Baltimore',
 'Los Angeles-Long Beach-Anaheim',
 'Los Angeles-Long Beach-Anaheim',
 'Phoenix',
 'Chicago',
 'Miami-Fort Lauderdale',
 'San Antonio',
 'Philadelphia',
 'Miami-Fort Lauderdale',
 'Boston',
 'Sacramento',
 'Chicago',
 'Bakersfield',
 'Oklahoma City',
 'Rochester',
 'Philadelphia',
 'Las Vegas',
 'Visalia',
 'Philadelphia',
 'Durham',
 'New York',
 'Bakersfield',
 'Miami-Fort Lauderdale',
 'Washington',
 'Washington',
 'Nashville',
 'Bakersfield',
 'San Jose',
 'Savannah',
 'Kansas City',
 'New York',
 'Baltimore',
 'Chicago',
 'Durham',
 'Phoenix',
 'Columbia',
 'Hanford',
 'Fayetteville',
 'Charleston',
 'Dallas-Fort Worth',
 'Miami-Fort Lauderdale',
 'Los Angeles-Long Beach-Anaheim',
 'San Francisco',
 'Nashville',
 'Portland',
 'San Francisco',
 'Santa Cruz',
 'Chicago',
 'Seattle',
 'Hickory',
 'Baton Rouge',
 'Houston',
 'Dallas-Fort Worth',
 'Los Angeles-Long Beach-Anaheim',
 'Visalia',
 'Columbus',
 'Charlotte',
 'Oxford',
 'Indianapolis',
 'Nashville',
 'Orlando',
 'Los Angeles-Long Beach-Anaheim',
 'Warner Robins',
 'Montgomery',
 'Nashville',
 'Jacksonville',
 'Washington',
 'Houston',
 'Spokane',
 'Houston',
 'St. Louis',
 'New York',
 'Greenville',
 'Charlotte',
 'Atlanta',
 'Charleston',
 'San Diego',
 'San Diego',
 'Los Angeles-Long Beach-Anaheim',
 'Pittsburgh',
 'New Haven',
 'Durham',
 'Portland',
 'Boston',
 'York',
 'Gainesville',
 'Austin',
 'New York',
 'Tampa',
 'St. Louis',
 'Phoenix',
 'San Diego',
 'Phoenix',
 'San Francisco',
 'Albuquerque',
 'San Antonio',
 'Austin',
 'Las Vegas',
 'Los Angeles-Long Beach-Anaheim',
 'San Francisco',
 'Clarksville',
 'Tulsa',
 'Seattle',
 'New York',
 'Atlanta',
 'Baltimore',
 'Charlotte',
 'Washington',
 'Phoenix',
 'Miami-Fort Lauderdale',
 'Longview',
 'Modesto',
 'Twin Falls',
 'Dallas-Fort Worth',
 'Kalispell',
 'Sacramento',
 'Phoenix',
 'Baltimore',
 'Orlando',
 'Riverside',
 'Columbus',
 'Chicago',
 'Eugene',
 'Chattanooga',
 'Nashville',
 'San Jose',
 'San Francisco',
 'Nashville',
 'Cincinnati',
 'Philadelphia',
 'Philadelphia',
 'Charlotte',
 'Miami-Fort Lauderdale',
 'Salina',
 'Atlanta',
 'San Diego',
 'Charlotte',
 'Cincinnati',
 'Phoenix',
 'New York',
 'New Orleans',
 'Raleigh',
 'Virginia Beach',
 'San Francisco',
 'Jackson',
 'Miami-Fort Lauderdale',
 'San Diego',
 'Elizabethtown',
 'Las Vegas',
 'Las Vegas',
 'Houston',
 'Virginia Beach',
 'Buffalo',
 'Louisville/Jefferson County',
 'El Paso',
 nan,
 'Atlanta',
 'Atlanta',
 'Albany',
 'Atlanta',
 'Miami-Fort Lauderdale',
 'Chicago',
 'Cincinnati',
 'Los Angeles-Long Beach-Anaheim',
 'Minneapolis-St Paul',
 'Tallahassee',
 'Austin',
 'Los Angeles-Long Beach-Anaheim',
 'San Francisco',
 'Nashville',
 'Los Angeles-Long Beach-Anaheim',
 'Austin',
 'New York',
 'Flint',
 'Las Vegas',
 'San Antonio',
 'Miami-Fort Lauderdale',
 'San Jose',
 'Austin',
 'Urban Honolulu',
 'San Jose',
 'Seattle',
 'Philadelphia',
 'New York',
 'Orlando',
 'Madison',
 'Pittsfield',
 'Washington',
 'Sacramento',
 'Ogden',
 nan,
 'Billings',
 'New York',
 'Houston',
 'Boston',
 'Philadelphia',
 'Urban Honolulu',
 'San Antonio',
 'Dallas-Fort Worth',
 'Starkville',
 'San Jose',
 'Miami-Fort Lauderdale',
 'Los Angeles-Long Beach-Anaheim',
 'Portland',
 'La Crosse',
 'Miami-Fort Lauderdale',
 'Myrtle Beach',
 'Miami-Fort Lauderdale',
 'Miami-Fort Lauderdale',
 'New Haven',
 'New York',
 'Riverside',
 'Seattle',
 'New York',
 'Dallas-Fort Worth',
 'Houston',
 'New York',
 'Atlanta',
 'Chicago',
 'Washington',
 'New York',
 'Atlanta',
 'Phoenix',
 'Madison',
 'Providence',
 'Boston',
 'Dallas-Fort Worth',
 'Tampa',
 'Cincinnati',
 'San Diego',
 'Orlando',
 'Marion',
 'New York',
 'San Diego',
 'Washington',
 'Washington',
 'Philadelphia',
 'San Diego',
 'Las Vegas',
 'Washington',
 'New York',
 'Lancaster',
 'Vallejo',
 'Detroit',
 'Phoenix',
 'Los Angeles-Long Beach-Anaheim',
 'San Jose',
 'Riverside',
 'Charleston',
 'Orlando',
 'Miami-Fort Lauderdale',
 'Bloomington',
 'Cincinnati',
 'Philadelphia',
 'St. Louis',
 'Atlanta',
 'New Orleans',
 'Los Angeles-Long Beach-Anaheim',
 'Austin',
 'Lubbock',
 'Boise City',
 'Philadelphia',
 'Little Rock',
 'Winston-Salem',
 'Los Angeles-Long Beach-Anaheim',
 'Myrtle Beach',
 'Dallas-Fort Worth',
 'Dayton',
 'San Diego',
 'Baltimore',
 'Charlotte',
 'Bakersfield',
 'San Francisco',
 'Oklahoma City',
 'Denver',
 'Augusta',
 'New York',
 'Brownsville',
 'Riverside',
 'San Francisco',
 'Orlando',
 'Columbia',
 'Blacksburg',
 'Memphis',
 'Medford',
 'Miami-Fort Lauderdale',
 'New York',
 'Lawton',
 'Raleigh',
 'Chicago',
 'Riverside',
 'Daytona Beach',
 'Bellingham',
 'Dallas-Fort Worth',
 'New York',
 'Miami-Fort Lauderdale',
 'Phoenix',
 'Dallas-Fort Worth',
 'Richmond',
 'Columbia',
 'San Antonio',
 'Ogden',
 'Chicago',
 'San Antonio',
 'Atlanta',
 'New York',
 'Houston',
 'Kennewick',
 'Portland',
 'Amarillo',
 'Riverside',
 'Memphis',
 'Philadelphia',
 'Miami-Fort Lauderdale',
 'Virginia Beach',
 'Canton',
 'Dallas-Fort Worth',
 'Hickory',
 'San Antonio',
 'Los Angeles-Long Beach-Anaheim',
 'San Jose',
 'Washington',
 'Chicago',
 'Detroit',
 'New York',
 'St. Louis',
 'Denver',
 'Mobile',
 'St. Louis',
 'San Diego',
 'Philadelphia',
 'Modesto',
 'Tampa',
 'Port St. Lucie',
 'Eugene',
 'Urban Honolulu',
 'Gulfport',
 'Davenport',
 'San Diego',
 'Fort Collins',
 'Laredo',
 'Baltimore',
 'Philadelphia',
 'San Diego',
 'Phoenix',
 'Raleigh',
 'Los Angeles-Long Beach-Anaheim',
 'Riverside',
 'Stamford',
 'New York',
 'Mankato',
 'Washington',
 'Indianapolis',
 'Phoenix',
 'Cincinnati',
 'Richmond',
 'Jacksonville',
 'Las Vegas',
 'Sacramento',
 nan,
 'Bangor',
 'St. Louis',
 'Cleveland',
 'Port St. Lucie',
 'New York',
 'San Antonio',
 'Cincinnati',
 'Atlanta',
 'Auburn',
 'Brownsville',
 'Bend',
 'Raleigh',
 'Miami-Fort Lauderdale',
 'Riverside',
 'Jacksonville',
 'Hilo',
 'Los Angeles-Long Beach-Anaheim',
 'Huntsville',
 'Urban Honolulu',
 'Los Angeles-Long Beach-Anaheim',
 'Clarksville',
 'Raleigh',
 'New York',
 'Athens',
 'Dallas-Fort Worth',
 'Miami-Fort Lauderdale',
 'New York',
 'Las Vegas',
 'Fort Myers',
 'Chicago',
 'Los Angeles-Long Beach-Anaheim',
 'Philadelphia',
 'Riverside',
 'Ventura',
 'Dallas-Fort Worth',
 'Phoenix',
 'Virginia Beach',
 'Washington',
 'Albuquerque',
 'Riverside',
 'Baltimore',
 'Los Angeles-Long Beach-Anaheim',
 'Raleigh',
 'Chicago',
 'Springfield',
 'Dallas-Fort Worth',
 'San Francisco',
 'New York',
 'Lakeland',
 'Minneapolis-St Paul',
 'Baltimore',
 'Lancaster',
 'Denver',
 'Philadelphia',
 'Tampa',
 'Phoenix',
 'Denver',
 'Kalamazoo',
 'Los Angeles-Long Beach-Anaheim',
 'San Antonio',
 'Dallas-Fort Worth',
 'Dallas-Fort Worth',
 'Tyler',
 'San Antonio',
 'Seattle',
 'Detroit',
 'Boulder',
 'Tampa',
 'Salem',
 'Philadelphia',
 'Miami-Fort Lauderdale',
 'Washington',
 'Columbus',
 'Las Vegas',
 'Bakersfield',
 'Los Angeles-Long Beach-Anaheim',
 'Albuquerque',
 'San Antonio',
 'Washington',
 'Portland',
 'Virginia Beach',
 'Oklahoma City',
 'Urban Honolulu',
 'Florence',
 'Springfield',
 'Denver',
 'Baton Rouge',
 'Dallas-Fort Worth',
 'Philadelphia',
 'Austin',
 'Pittsburgh',
 'New Orleans',
 'Riverside',
 'Charlotte',
 'Colorado Springs',
 'Austin',
 'Chicago',
 'McAllen',
 'Richmond',
 'Medford',
 'Fargo',
 'Riverside',
 'Michigan City',
 'Fayetteville',
 'Sioux Falls',
 'North Port-Sarasota-Bradenton',
 'Melbourne',
 'Miami-Fort Lauderdale',
 'Greenville',
 'Los Angeles-Long Beach-Anaheim',
 'Charleston',
 'Albany',
 'Phoenix',
 'Buffalo',
 'St. Louis',
 'New York',
 'Portland',
 'Louisville/Jefferson County',
 'Virginia Beach',
 'Las Vegas',
 'Dallas-Fort Worth',
 'Houston',
 'Dallas-Fort Worth',
 'Houston',
 'Dallas-Fort Worth',
 'Wichita',
 'Reno',
 'San Diego',
 'Raleigh',
 'Houston',
 'Washington',
 'Pittsburgh',
 'Phoenix',
 'Miami-Fort Lauderdale',
 'Oklahoma City',
 'Miami-Fort Lauderdale',
 'New York',
 'Phoenix',
 'Los Angeles-Long Beach-Anaheim',
 'Atlanta',
 'New York',
 'Toledo',
 'Miami-Fort Lauderdale',
 'Bloomington',
 'New York',
 'Miami-Fort Lauderdale',
 'Atlanta',
 'Rapid City',
 'Memphis',
 'Winston-Salem',
 'Houston',
 'Phoenix',
 'Columbus',
 'Lafayette',
 'Philadelphia',
 'San Jose',
 'Memphis',
 'New York',
 'Grand Forks',
 'Killeen',
 'Oshkosh',
 'Phoenix',
 'Tampa',
 'Minneapolis-St Paul',
 'Tampa',
 'New York',
 'Philadelphia',
 'Phoenix',
 'Cincinnati',
 'Visalia',
 'Ventura',
 'Raleigh',
 'Fayetteville',
 'Springfield',
 'Knoxville',
 'Minneapolis-St Paul',
 'San Antonio',
 'Binghamton',
 'Urban Honolulu',
 'Dallas-Fort Worth',
 'Cleveland',
 'Kingsport',
 'Seattle',
 'Boston',
 'Burlington',
 'Los Angeles-Long Beach-Anaheim',
 'Chicago',
 'Minneapolis-St Paul',
 'Houma',
 'Detroit',
 'Tuscaloosa',
 'Denver',
 'Phoenix',
 'Orlando',
 'Williamsport',
 'Raleigh',
 'San Diego',
 'Albuquerque',
 'Birmingham',
 'Houston',
 'San Francisco',
 'San Diego',
 'New Haven',
 'Columbus',
 'Buffalo',
 'Fresno',
 'Dallas-Fort Worth',
 'Green Bay',
 'Oklahoma City',
 'Los Angeles-Long Beach-Anaheim',
 'Phoenix',
 'Miami-Fort Lauderdale',
 'Riverside',
 'Tampa',
 'Raleigh',
 'Redding',
 'Lexington',
 'Hilton Head Island',
 'Minneapolis-St Paul',
 'Virginia Beach',
 'Philadelphia',
 'Raleigh',
 'Charlotte',
 'El Paso',
 'San Diego',
 'Sacramento',
 'Orlando',
 'Albany',
 'Allentown',
 'Wilmington',
 'Houston',
 'Fort Collins',
 'Pittsburgh',
 'Asheville',
 'Charlotte',
 'Dallas-Fort Worth',
 'Daytona Beach',
 'Santa Fe',
 'Buffalo',
 'Tulsa',
 'Dallas-Fort Worth',
 'Minneapolis-St Paul',
 'Santa Maria-Santa Barbara',
 'New York',
 'Philadelphia',
 'Charlotte',
 'Denver',
 'Kansas City',
 'Houston',
 'Los Angeles-Long Beach-Anaheim',
 'Riverside',
 'New York',
 'Chicago',
 'Corvallis',
 'Los Angeles-Long Beach-Anaheim',
 'San Francisco',
 'Milwaukee',
 'Stockton',
 'Sacramento',
 'Washington',
 'Riverside',
 'Owensboro',
 'Wooster',
 'Los Angeles-Long Beach-Anaheim',
 'New York',
 'Detroit',
 'Los Angeles-Long Beach-Anaheim',
 'Seattle',
 'Greenville',
 'Los Angeles-Long Beach-Anaheim',
 'Myrtle Beach',
 'Fairmont',
 'Los Angeles-Long Beach-Anaheim',
 'Winston-Salem',
 'Jacksonville',
 'Los Angeles-Long Beach-Anaheim',
 'Columbus',
 'Lynchburg',
 'Columbus',
 'Riverside',
 'Indianapolis',
 'Killeen',
 'Miami-Fort Lauderdale',
 'Riverside',
 'Seattle',
 'Daytona Beach',
 'Minneapolis-St Paul',
 'Nashville',
 'Dubuque',
 'Los Angeles-Long Beach-Anaheim',
 'San Antonio',
 'Seattle',
 'Trenton',
 'Morgantown',
 'Miami-Fort Lauderdale',
 'Miami-Fort Lauderdale',
 'Los Angeles-Long Beach-Anaheim',
 'Charlotte',
 'Albuquerque',
 'Dallas-Fort Worth',
 'Tucson',
 'New York',
 'Detroit',
 'Portland',
 ...]

In [8]:
df_metro = df[df.Metro == 'Houston']
df_metro

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
2,91982,77494,Katy,TX,Houston,Harris,3,210400.0,212200.0,212200.0,...,321000,320600,320200,320400,320800,321200,321200,323000,326900,329900
5,91733,77084,Houston,TX,Houston,Harris,6,95000.0,95200.0,95400.0,...,157900,158700,160200,161900,162800,162800,162800,162900,163500,164300
8,91940,77449,Katy,TX,Houston,Harris,9,95400.0,95600.0,95800.0,...,166800,167400,168400,169600,170900,172300,173300,174200,175400,176200
22,92036,77573,League City,TX,Houston,Galveston,23,141400.0,141000.0,140600.0,...,249800,251300,252300,252400,252300,253100,254700,257100,259800,261400
23,92045,77584,Pearland,TX,Houston,Brazoria,24,138500.0,138700.0,139200.0,...,249100,249900,250500,250700,251000,251400,251900,253200,255100,256500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11091,91996,77514,Anahuac,TX,Houston,Chambers,11092,51700.0,51900.0,52200.0,...,130000,129700,129100,129200,129900,130900,131600,133100,135000,136400
11934,91699,77050,Houston,TX,Houston,Harris,11935,49200.0,49500.0,49700.0,...,104200,107000,109500,111200,110800,110900,112900,114900,115400,115200
12194,92078,77650,Port Bolivar,TX,Houston,Galveston,12195,131500.0,130800.0,130100.0,...,225200,228300,230600,233100,235600,238300,240300,243500,246400,247500
12497,92009,77534,Danbury,TX,Houston,Brazoria,12498,74500.0,74900.0,75300.0,...,165300,163500,162600,162500,162400,162800,163000,162800,163500,164800
14248,92039,77577,Liverpool,TX,Houston,Brazoria,14249,60700.0,61100.0,61400.0,...,155700,151300,147400,146500,145900,145600,145000,145100,147300,149200

In [9]:
sorted(list(df_metro.RegionName))

[77002,
 77003,
 77004,
 77005,
 77006,
 77007,
 77008,
 77013,
 77014,
 77015,
 77016,
 77017,
 77018,
 77019,
 77020,
 77021,
 77024,
 77025,
 77027,
 77028,
 77029,
 77030,
 77031,
 77032,
 77033,
 77034,
 77035,
 77036,
 77037,
 77038,
 77039,
 77040,
 77041,
 77042,
 77043,
 77044,
 77045,
 77047,
 77048,
 77049,
 77050,
 77051,
 77053,
 77054,
 77055,
 77056,
 77057,
 77058,
 77059,
 77060,
 77061,
 77062,
 77063,
 77064,
 77065,
 77066,
 77067,
 77068,
 77069,
 77070,
 77071,
 77072,
 77073,
 77074,
 77075,
 77077,
 77078,
 77079,
 77080,
 77081,
 77082,
 77083,
 77084,
 77085,
 77086,
 77087,
 77088,
 77089,
 77090,
 77091,
 77092,
 77093,
 77094,
 77095,
 77096,
 77098,
 77099,
 77301,
 77302,
 77303,
 77304,
 77316,
 77318,
 77338,
 77339,
 77345,
 77346,
 77354,
 77355,
 77356,
 77357,
 77362,
 77365,
 77372,
 77373,
 77375,
 77377,
 77378,
 77379,
 77380,
 77381,
 77382,
 77384,
 77385,
 77386,
 77388,
 77389,
 77396,
 77401,
 77406,
 77407,
 77418,
 77422,
 77429,
 77433,
 77441,
 77447,
 77449,
 77450,
 77459,
 77469,
 77471,
 77474,
 77477,
 77478,
 77479,
 77486,
 77489,
 77493,
 77494,
 77498,
 77502,
 77503,
 77504,
 77505,
 77506,
 77510,
 77511,
 77514,
 77515,
 77517,
 77518,
 77520,
 77521,
 77523,
 77530,
 77531,
 77532,
 77534,
 77536,
 77539,
 77541,
 77545,
 77546,
 77547,
 77550,
 77551,
 77554,
 77562,
 77563,
 77565,
 77566,
 77568,
 77571,
 77573,
 77577,
 77578,
 77581,
 77583,
 77584,
 77586,
 77587,
 77590,
 77591,
 77598,
 77650,
 77665]

In [10]:
df_set = df[(df.State == 'TX') & (df.City == 'Houston')]
df_set

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
5,91733,77084,Houston,TX,Houston,Harris,6,95000.0,95200.0,95400.0,...,157900,158700,160200,161900,162800,162800,162800,162900,163500,164300
44,91685,77036,Houston,TX,Houston,Harris,45,120400.0,118700.0,117300.0,...,174900,174600,175000,176000,177200,177700,177700,179800,185100,189800
63,91726,77077,Houston,TX,Houston,Harris,64,177100.0,180000.0,182700.0,...,309600,310000,310800,311600,311800,311200,310500,311400,313800,315900
182,91744,77095,Houston,TX,Houston,Harris,183,131700.0,131300.0,131100.0,...,208900,210200,210700,211200,212300,213100,212800,214300,217500,219600
279,91731,77082,Houston,TX,Houston,Harris,280,101600.0,101300.0,100800.0,...,165800,166600,167600,168400,169000,169800,170800,171800,172500,172900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7892,91727,77078,Houston,TX,Houston,Harris,7893,45700.0,45700.0,45700.0,...,93400,94700,96700,98100,97500,96600,96600,97500,98500,99400
8125,91717,77068,Houston,TX,Houston,Harris,8126,136300.0,135900.0,135500.0,...,205700,205700,206200,206800,207100,207600,207800,208700,210300,211500
8230,91681,77032,Houston,TX,Houston,Harris,8231,57100.0,57100.0,57000.0,...,104800,105600,106500,108200,111200,113600,115600,117400,118800,119200
8357,91743,77094,Houston,TX,Houston,Harris,8358,356300.0,357700.0,358800.0,...,375100,374400,374100,374700,375300,375000,373400,372800,373600,373900
11934,91699,77050,Houston,TX,Houston,Harris,11935,49200.0,49500.0,49700.0,...,104200,107000,109500,111200,110800,110900,112900,114900,115400,115200

In [11]:
sum(df_set.CountyName == 'Harris')

86

In [12]:
df_set = df_set.sort_values(by='SizeRank')
df_set

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
5,91733,77084,Houston,TX,Houston,Harris,6,95000.0,95200.0,95400.0,...,157900,158700,160200,161900,162800,162800,162800,162900,163500,164300
44,91685,77036,Houston,TX,Houston,Harris,45,120400.0,118700.0,117300.0,...,174900,174600,175000,176000,177200,177700,177700,179800,185100,189800
63,91726,77077,Houston,TX,Houston,Harris,64,177100.0,180000.0,182700.0,...,309600,310000,310800,311600,311800,311200,310500,311400,313800,315900
182,91744,77095,Houston,TX,Houston,Harris,183,131700.0,131300.0,131100.0,...,208900,210200,210700,211200,212300,213100,212800,214300,217500,219600
279,91731,77082,Houston,TX,Houston,Harris,280,101600.0,101300.0,100800.0,...,165800,166600,167600,168400,169000,169800,170800,171800,172500,172900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7892,91727,77078,Houston,TX,Houston,Harris,7893,45700.0,45700.0,45700.0,...,93400,94700,96700,98100,97500,96600,96600,97500,98500,99400
8125,91717,77068,Houston,TX,Houston,Harris,8126,136300.0,135900.0,135500.0,...,205700,205700,206200,206800,207100,207600,207800,208700,210300,211500
8230,91681,77032,Houston,TX,Houston,Harris,8231,57100.0,57100.0,57000.0,...,104800,105600,106500,108200,111200,113600,115600,117400,118800,119200
8357,91743,77094,Houston,TX,Houston,Harris,8358,356300.0,357700.0,358800.0,...,375100,374400,374100,374700,375300,375000,373400,372800,373600,373900
11934,91699,77050,Houston,TX,Houston,Harris,11935,49200.0,49500.0,49700.0,...,104200,107000,109500,111200,110800,110900,112900,114900,115400,115200

In [13]:
df_set = df_set[:15]
df_set

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
5,91733,77084,Houston,TX,Houston,Harris,6,95000.0,95200.0,95400.0,...,157900,158700,160200,161900,162800,162800,162800,162900,163500,164300
44,91685,77036,Houston,TX,Houston,Harris,45,120400.0,118700.0,117300.0,...,174900,174600,175000,176000,177200,177700,177700,179800,185100,189800
63,91726,77077,Houston,TX,Houston,Harris,64,177100.0,180000.0,182700.0,...,309600,310000,310800,311600,311800,311200,310500,311400,313800,315900
182,91744,77095,Houston,TX,Houston,Harris,183,131700.0,131300.0,131100.0,...,208900,210200,210700,211200,212300,213100,212800,214300,217500,219600
279,91731,77082,Houston,TX,Houston,Harris,280,101600.0,101300.0,100800.0,...,165800,166600,167600,168400,169000,169800,170800,171800,172500,172900
321,91706,77057,Houston,TX,Houston,Harris,322,448800.0,450100.0,451500.0,...,566300,566500,567200,566600,562200,554300,547900,548400,557300,565000
387,91656,77007,Houston,TX,Houston,Harris,388,311900.0,308000.0,303500.0,...,402100,403600,405600,407100,406600,405500,405000,406300,409500,411700
529,91719,77070,Houston,TX,Houston,Harris,530,120000.0,119600.0,119200.0,...,192300,192700,193400,193900,194500,194800,195000,195600,197000,197900
817,91730,77081,Houston,TX,Houston,Harris,818,273800.0,275500.0,277200.0,...,372000,371700,370000,370200,372300,374800,379200,384600,389200,391800
819,91712,77063,Houston,TX,Houston,Harris,820,224200.0,228000.0,231800.0,...,334100,336700,337600,337400,338900,339600,337000,339400,348700,355800
846,91691,77042,Houston,TX,Houston,Harris,847,253000.0,257500.0,261800.0,...,383700,381600,381300,381800,382000,382600,384100,386500,388800,389600
944,91721,77072,Houston,TX,Houston,Harris,945,65900.0,65900.0,65900.0,...,123500,122900,122800,123700,124800,125900,125700,126600,129600,132300
1028,91664,77015,Houston,TX,Houston,Harris,1029,66100.0,66100.0,66200.0,...,125500,125900,126200,127100,128500,129700,130400,131400,133000,134100
1041,91657,77008,Houston,TX,Houston,Harris,1042,236200.0,234800.0,233500.0,...,418500,421000,423500,425500,426500,427600,428600,430800,434700,437600
1066,91689,77040,Houston,TX,Houston,Harris,1067,97300.0,97100.0,96900.0,...,163400,164600,165200,166300,168600,171100,172700,173900,175200,175900

In [14]:
df_set.isna().sum()

RegionID      0
RegionName    0
City          0
State         0
Metro         0
             ..
2017-12       0
2018-01       0
2018-02       0
2018-03       0
2018-04       0
Length: 272, dtype: int64

Filtering dataset to the top 15 Size Rank in Houston,TX Harris County.

In [15]:
df_set.reset_index(drop=True, inplace=True)
df_set

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
0,91733,77084,Houston,TX,Houston,Harris,6,95000.0,95200.0,95400.0,...,157900,158700,160200,161900,162800,162800,162800,162900,163500,164300
1,91685,77036,Houston,TX,Houston,Harris,45,120400.0,118700.0,117300.0,...,174900,174600,175000,176000,177200,177700,177700,179800,185100,189800
2,91726,77077,Houston,TX,Houston,Harris,64,177100.0,180000.0,182700.0,...,309600,310000,310800,311600,311800,311200,310500,311400,313800,315900
3,91744,77095,Houston,TX,Houston,Harris,183,131700.0,131300.0,131100.0,...,208900,210200,210700,211200,212300,213100,212800,214300,217500,219600
4,91731,77082,Houston,TX,Houston,Harris,280,101600.0,101300.0,100800.0,...,165800,166600,167600,168400,169000,169800,170800,171800,172500,172900
5,91706,77057,Houston,TX,Houston,Harris,322,448800.0,450100.0,451500.0,...,566300,566500,567200,566600,562200,554300,547900,548400,557300,565000
6,91656,77007,Houston,TX,Houston,Harris,388,311900.0,308000.0,303500.0,...,402100,403600,405600,407100,406600,405500,405000,406300,409500,411700
7,91719,77070,Houston,TX,Houston,Harris,530,120000.0,119600.0,119200.0,...,192300,192700,193400,193900,194500,194800,195000,195600,197000,197900
8,91730,77081,Houston,TX,Houston,Harris,818,273800.0,275500.0,277200.0,...,372000,371700,370000,370200,372300,374800,379200,384600,389200,391800
9,91712,77063,Houston,TX,Houston,Harris,820,224200.0,228000.0,231800.0,...,334100,336700,337600,337400,338900,339600,337000,339400,348700,355800
10,91691,77042,Houston,TX,Houston,Harris,847,253000.0,257500.0,261800.0,...,383700,381600,381300,381800,382000,382600,384100,386500,388800,389600
11,91721,77072,Houston,TX,Houston,Harris,945,65900.0,65900.0,65900.0,...,123500,122900,122800,123700,124800,125900,125700,126600,129600,132300
12,91664,77015,Houston,TX,Houston,Harris,1029,66100.0,66100.0,66200.0,...,125500,125900,126200,127100,128500,129700,130400,131400,133000,134100
13,91657,77008,Houston,TX,Houston,Harris,1042,236200.0,234800.0,233500.0,...,418500,421000,423500,425500,426500,427600,428600,430800,434700,437600
14,91689,77040,Houston,TX,Houston,Harris,1067,97300.0,97100.0,96900.0,...,163400,164600,165200,166300,168600,171100,172700,173900,175200,175900

In [16]:
df_set.RegionName

0     77084
1     77036
2     77077
3     77095
4     77082
5     77057
6     77007
7     77070
8     77081
9     77063
10    77042
11    77072
12    77015
13    77008
14    77040
Name: RegionName, dtype: int64

In [17]:
df_set.loc[:,'2012-01': '2017-12']

,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,...,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12
0,113200.0,112800.0,112600.0,112000.0,111800.0,111700.0,111700.0,111800.0,111800.0,111600.0,...,157300,157600,157700,157700,157900,158700,160200,161900,162800,162800
1,124500.0,123400.0,123200.0,123200.0,122800.0,122500.0,122800.0,123600.0,124100.0,124100.0,...,171300,172900,174900,175500,174900,174600,175000,176000,177200,177700
2,212900.0,211200.0,210200.0,208800.0,208000.0,208300.0,210300.0,214500.0,218300.0,220000.0,...,308500,308900,309400,309600,309600,310000,310800,311600,311800,311200
3,151600.0,151600.0,151600.0,151100.0,150500.0,150500.0,151000.0,151600.0,151700.0,151400.0,...,208400,208000,208000,208200,208900,210200,210700,211200,212300,213100
4,113500.0,114000.0,114600.0,114700.0,114600.0,115200.0,115900.0,116000.0,115800.0,115800.0,...,161500,163100,164700,165400,165800,166600,167600,168400,169000,169800
5,434800.0,439000.0,443300.0,444800.0,447000.0,449600.0,452100.0,455300.0,457000.0,455300.0,...,567900,564500,563200,564500,566300,566500,567200,566600,562200,554300
6,296200.0,297100.0,298500.0,299000.0,299400.0,300600.0,302500.0,304700.0,306000.0,306200.0,...,397400,397900,398900,400500,402100,403600,405600,407100,406600,405500
7,140500.0,140700.0,141400.0,141600.0,141300.0,141400.0,141800.0,142200.0,142100.0,141400.0,...,190000,191000,191900,192300,192300,192700,193400,193900,194500,194800
8,255700.0,256900.0,260700.0,264500.0,266600.0,267900.0,267400.0,266900.0,266500.0,267400.0,...,366700,367400,369300,370900,372000,371700,370000,370200,372300,374800
9,242500.0,242000.0,241300.0,240700.0,241400.0,242000.0,241300.0,241900.0,243200.0,244500.0,...,340000,337900,336000,334300,334100,336700,337600,337400,338900,339600
10,258600.0,260200.0,261800.0,263000.0,264200.0,265700.0,267800.0,269900.0,270200.0,269200.0,...,378600,380500,385200,386100,383700,381600,381300,381800,382000,382600
11,81600.0,81700.0,81900.0,82100.0,82000.0,81400.0,81400.0,81900.0,82200.0,82000.0,...,122300,123400,124200,124400,123500,122900,122800,123700,124800,125900
12,84300.0,84100.0,84300.0,84500.0,84700.0,84700.0,84800.0,85200.0,85500.0,85500.0,...,121700,122600,123600,124700,125500,125900,126200,127100,128500,129700
13,294400.0,295600.0,296600.0,296300.0,296100.0,296300.0,296800.0,297800.0,298800.0,299600.0,...,412500,413100,414200,416300,418500,421000,423500,425500,426500,427600
14,116700.0,116900.0,117400.0,117300.0,117400.0,118100.0,118700.0,119200.0,119500.0,119500.0,...,158400,160000,161100,162100,163400,164600,165200,166300,168600,171100

In [18]:
def get_datetimes(df):
    """
    Takes a dataframe:
    returns only those column names that can be converted into datetime objects 
    as datetime objects.
    NOTE number of returned columns may not match total number of columns in passed dataframe
    """
    
    return pd.to_datetime(df.columns.values[1:], format='%Y-%m')

In [19]:
date_time_idx = get_datetimes(df_set.loc[:, '2012-01': '2017-12'])

In [20]:
date_time_idx

DatetimeIndex(['2012-02-01', '2012-03-01', '2012-04-01', '2012-05-01',
               '2012-06-01', '2012-07-01', '2012-08-01', '2012-09-01',
               '2012-10-01', '2012-11-01', '2012-12-01', '2013-01-01',
               '2013-02-01', '2013-03-01', '2013-04-01', '2013-05-01',
               '2013-06-01', '2013-07-01', '2013-08-01', '2013-09-01',
               '2013-10-01', '2013-11-01', '2013-12-01', '2014-01-01',
               '2014-02-01', '2014-03-01', '2014-04-01', '2014-05-01',
               '2014-06-01', '2014-07-01', '2014-08-01', '2014-09-01',
               '2014-10-01', '2014-11-01', '2014-12-01', '2015-01-01',
               '2015-02-01', '2015-03-01', '2015-04-01', '2015-05-01',
               '2015-06-01', '2015-07-01', '2015-08-01', '2015-09-01',
               '2015-10-01', '2015-11-01', '2015-12-01', '2016-01-01',
               '2016-02-01', '2016-03-01', '2016-04-01', '2016-05-01',
               '2016-06-01', '2016-07-01', '2016-08-01', '2016-09-01',
               '2016-10-01', '2016-11-01', '2016-12-01', '2017-01-01',
               '2017-02-01', '2017-03-01', '2017-04-01', '2017-05-01',
               '2017-06-01', '2017-07-01', '2017-08-01', '2017-09-01',
               '2017-10-01', '2017-11-01', '2017-12-01'],
              dtype='datetime64[ns]', freq=None)